Add support for UpsampleNearest2D/backward with scale
pytorch/xla pull request #2597
Opened 2020-10-31 03:32 UTC by JackCaoG

this is to fix https://github.com/pytorch/xla/issues/2588
`upsample_nearest2d ` with scale will use another C++ api than the existing one.

2020-11-01 07:30 UTC, davidel requested changes

2020-11-01 07:30 UTC, davidel commented on torch_xla/csrc/aten_xla_type.cpp
> +// input is in format of {N, C, H, W} and the output will be {H, W}.
`The input ...`

2020-11-01 07:30 UTC, davidel commented on torch_xla/csrc/aten_xla_type.cpp
> +std::vector<xla::int64> getOutputSizeWithScale(
Camels belong in the desert 😄 ... `GetOutputSizeWithScale()`

2020-11-01 07:30 UTC, davidel commented on torch_xla/csrc/aten_xla_type.cpp
> +    XLA_CHECK(!scale_factors);
I find it less `indenty` to just follow up in these cases without opening an `else` indentation 😉

2020-11-03 09:16 UTC, davidel approved these changes
Minor nit otherwise LGTM!

2020-11-03 09:16 UTC, davidel commented on torch_xla/csrc/aten_xla_type.cpp
> +    c10::optional<at::ArrayRef<double>> scale_factors,
Even though pytorch passes those by value (these are refs, so their storage/copy is small), I think it is best to stick with the policy to pass optional values by `const&` as passing by value involves copies.

2020-11-04 05:50 UTC, davidel approved these changes

2020-11-04 11:58 UTC, WingsleyLui commented
@davidel @JackCaoG this solution does not work for torch-xla-1.7 but for torch-xla-1.6

2020-11-04 16:25 UTC, davidel commented
> @davidel @JackCaoG this solution does not work for torch-xla-1.7 but for torch-xla-1.6

In which way does not work?

2020-11-04 17:12 UTC, WingsleyLui commented
> > @davidel @JackCaoG this solution does not work for torch-xla-1.7 but for torch-xla-1.6
> 
> In which way does not work?

Sorry my bad. Works for 1.6 and does not work on 1.7

2020-11-04 18:17 UTC, JackCaoG commented
> > > @davidel @JackCaoG this solution does not work for torch-xla-1.7 but for torch-xla-1.6
> > 
> > 
> > In which way does not work?
> 
> Sorry my bad. Works for 1.6 and does not work on 1.7

@WingsleyLui Could you give a little bit more context? We don't intent to backport this op, so it will most likely be in our next release and it is working with the current pytorch head.

2020-11-04 22:29 UTC, merged

2020-11-05 02:02 UTC, WingsleyLui commented
Hi @JackCaoG ! I open an issue (#2603) to seek help for BigGAN, in which I found `aten::random_` and `aten::upsample_nearest2d`. I attached a demo after fixing upsample according to #2588, but found this doesn't work for `torch-xla-1.7`:

Simply I did this on a single TPU v3-8 on Google Cloud. I request computing resources as the same as the [resnet50 tut](https://cloud.google.com/tpu/docs/tutorials/resnet-pytorch). Just activate env by conda: `conda activate torch-xla-1.6` and `conda activate torch-xla-1.7`. 

```python
import torch
import torch.nn as nn
from torch.nn import init
import torch.optim as optim
import torch.nn.functional as F


# xla imports
import torch_xla.core.xla_model as xm
import torch_xla.distributed.data_parallel as dp
import torch_xla.debug.metrics as met

from argparse import ArgumentParser

class InterpolateNearest2d(nn.Module):
    """
    Custom implementation of nn.Upsample because pytroch/xla
    does not yet support scale_factor and needs to be provided with
    the output_size
    """

    def __init__(self, scale_factor=2):
        """
        Create an InterpolateNearest module

        Args:
            scale_factor (int, optional): Output size multiplier. Defaults to 2.
        """
        super().__init__()
        self.scale_factor = scale_factor

    def forward(self, x):
        """
        Interpolate x in "nearest" mode on its last 2 dimensions

        Args:
            x (torch.Tensor): input to interpolate

        Returns:
            torch.Tensor: upsampled tensor with shape
                (...x.shape, x.shape[-2] * scale_factor, x.shape[-1] * scale_factor)
        """
        return nn.functional.interpolate(
            x,
            size=(x.shape[-2] * self.scale_factor, x.shape[-1] * self.scale_factor),
            mode="nearest",
        )
if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("--upsample", action="store_true", default=False)
    parser.add_argument("--random", action="store_true", default=False)
    args = parser.parse_args()

    device = xm.xla_device()
    x = torch.randn(2,3,128,128, device=device)
    # y = torch.randint(2,5,(12,),device=device)  # aten::random_
    upsample = InterpolateNearest2d(scale_factor=2)
    
    if args.upsample:
        o = upsample(x)
        # o = F.interpolate(x, scale_factor=2)
    
    if args.random:
        x.random_(100)
        
        # torch.randint callsback `aten::random_`, too 
        # x = torch.randint(0,10,(20,)device=device)

    print(met.metrics_report())
```

For `torch-xla-1.7`  :

```shell
(torch-xla-1.7) supercomputer_ai@gan:~/BigGAN-Pytorch-TPU$ python misc.py --upsample
Metric: CompileTime
  TotalSamples: 1
  Accumulator: 082ms289.274us
  Percentiles: 1%=082ms289.274us; 5%=082ms289.274us; 10%=082ms289.274us; 20%=082ms289.274us; 50%=082ms289.274us; 80%=082ms289.274us; 90%=082ms289.274us; 95%=082ms289.274us; 99%=082ms289.274us
Metric: DeviceLockWait
  TotalSamples: 1
  Accumulator: 004.310us
  Percentiles: 1%=004.310us; 5%=004.310us; 10%=004.310us; 20%=004.310us; 50%=004.310us; 80%=004.310us; 90%=004.310us; 95%=004.310us; 99%=004.310us
Metric: ExecuteTime
  TotalSamples: 1
  Accumulator: 009ms707.524us
  Percentiles: 1%=009ms707.524us; 5%=009ms707.524us; 10%=009ms707.524us; 20%=009ms707.524us; 50%=009ms707.524us; 80%=009ms707.524us; 90%=009ms707.524us; 95%=009ms707.524us; 99%=009ms707.524us
Metric: InboundData
  TotalSamples: 1
  Accumulator: 384.00KB
  Percentiles: 1%=384.00KB; 5%=384.00KB; 10%=384.00KB; 20%=384.00KB; 50%=384.00KB; 80%=384.00KB; 90%=384.00KB; 95%=384.00KB; 99%=384.00KB
Metric: InputOutputAliasCount
  TotalSamples: 1
  Accumulator: 1.00
  Percentiles: 1%=1.00; 5%=1.00; 10%=1.00; 20%=1.00; 50%=1.00; 80%=1.00; 90%=1.00; 95%=1.00; 99%=1.00
Metric: OutboundData
  TotalSamples: 1
  Accumulator: 8.00B
  Percentiles: 1%=8.00B; 5%=8.00B; 10%=8.00B; 20%=8.00B; 50%=8.00B; 80%=8.00B; 90%=8.00B; 95%=8.00B; 99%=8.00B
Metric: ReleaseDataHandlesTime
  TotalSamples: 1
  Accumulator: 006ms020.423us
  Percentiles: 1%=006ms020.423us; 5%=006ms020.423us; 10%=006ms020.423us; 20%=006ms020.423us; 50%=006ms020.423us; 80%=006ms020.423us; 90%=006ms020.423us; 95%=006ms020.423us; 99%=006ms020.423us
Metric: TensorsGraphSize
  TotalSamples: 1
  Accumulator: 10.00
  Percentiles: 1%=10.00; 5%=10.00; 10%=10.00; 20%=10.00; 50%=10.00; 80%=10.00; 90%=10.00; 95%=10.00; 99%=10.00
Metric: TransferFromServerTime
  TotalSamples: 1
  Accumulator: 010ms949.833us
  Percentiles: 1%=010ms949.833us; 5%=010ms949.833us; 10%=010ms949.833us; 20%=010ms949.833us; 50%=010ms949.833us; 80%=010ms949.833us; 90%=010ms949.833us; 95%=010ms949.833us; 99%=010ms949.833us
Metric: TransferToServerTime
  TotalSamples: 1
  Accumulator: 011ms832.662us
  Percentiles: 1%=011ms832.662us; 5%=011ms832.662us; 10%=011ms832.662us; 20%=011ms832.662us; 50%=011ms832.662us; 80%=011ms832.662us; 90%=011ms832.662us; 95%=011ms832.662us; 99%=011ms832.662us
Metric: TransferToServerTransformTime
  TotalSamples: 1
  Accumulator: 004ms527.145us
  Percentiles: 1%=004ms527.145us; 5%=004ms527.145us; 10%=004ms527.145us; 20%=004ms527.145us; 50%=004ms527.145us; 80%=004ms527.145us; 90%=004ms527.145us; 95%=004ms527.145us; 99%=004ms527.145us
Counter: CreateCompileHandles
  Value: 1
Counter: CreateDataHandles
  Value: 2
Counter: CreateXlaTensor
  Value: 2
Counter: DestroyDataHandles
  Value: 1
Counter: ReleaseDataHandles
  Value: 1
Counter: UncachedCompile
  Value: 1
Counter: XRTAllocateFromTensor_Empty
  Value: 1
Counter: XrtCompile_Empty
  Value: 128
Counter: XrtExecuteChained_Empty
  Value: 128
Counter: XrtExecute_Empty
  Value: 128
Counter: XrtMemoryInfo_Empty
  Value: 128
Counter: XrtRead_Empty
  Value: 128
Counter: XrtReleaseAllocationHandle_Empty
  Value: 128
Counter: XrtReleaseCompileHandle_Empty
  Value: 128
Counter: XrtSessionCount
  Value: 2
Counter: XrtSubTuple_Empty
  Value: 128
Counter: aten::upsample_nearest2d
  Value: 1
Counter: xla::empty
  Value: 1
Counter: xla::normal_
  Value: 1
Metric: XrtAllocateFromTensor
  TotalSamples: 2
  Accumulator: 113ms811.793us
  Mean: 056ms405.897us
  StdDev: 056ms848.464us
  Rate: 0.0112314 / second
  Percentiles: 25%=557.432us; 50%=112ms254.361us; 80%=112ms254.361us; 90%=112ms254.361us; 95%=112ms254.361us; 99%=112ms254.361us
Metric: XrtCompile
  TotalSamples: 2
  Accumulator: 863ms772.203us
  Mean: 431ms386.101us
  StdDev: 431ms054.907us
  Rate: 0.0112871 / second
  Percentiles: 25%=331.195us; 50%=862ms441.008us; 80%=862ms441.008us; 90%=862ms441.008us; 95%=862ms441.008us; 99%=862ms441.008us
Metric: XrtExecute
  TotalSamples: 2
  Accumulator: 004ms163.561us
  Mean: 002ms081.780us
  StdDev: 753.573us
  Rate: 0.0112875 / second
  Percentiles: 25%=001ms328.207us; 50%=003ms835.354us; 80%=003ms835.354us; 90%=003ms835.354us; 95%=003ms835.354us; 99%=003ms835.354us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 2
  Accumulator: 002ms475.749us
  Mean: 001ms237.874us
  StdDev: 162.733us
  Rate: 0.0112876 / second
  Percentiles: 25%=001ms075.141us; 50%=001ms400.608us; 80%=001ms400.608us; 90%=001ms400.608us; 95%=001ms400.608us; 99%=001ms400.608us
Metric: XrtReleaseAllocation
  TotalSamples: 2
  Accumulator: 052.247us
  Mean: 026.123us
  StdDev: 001.260us
  Rate: 0.0112877 / second
  Percentiles: 25%=024.863us; 50%=027.384us; 80%=027.384us; 90%=027.384us; 95%=027.384us; 99%=027.384us

```

For `torch-xla-1.6`  :

```shell
(torch-xla-1.6) supercomputer_ai@gan:~/BigGAN-Pytorch-TPU$ python misc.py --upsample
Metric: OutboundData
  TotalSamples: 1
  Accumulator: 8.00B
  Percentiles: 1%=8.00B; 5%=8.00B; 10%=8.00B; 20%=8.00B; 50%=8.00B; 80%=8.00B; 90%=8.00B; 95%=8.00B; 99%=8.00B
Metric: TransferToServerTime
  TotalSamples: 1
  Accumulator: 018ms570.581us
  Percentiles: 1%=018ms570.581us; 5%=018ms570.581us; 10%=018ms570.581us; 20%=018ms570.581us; 50%=018ms570.581us; 80%=018ms570.581us; 90%=018ms570.581us; 95%=018ms570.581us; 99%=018ms570.581us
Metric: [...]