Sync TF: libtpu.so API breakage
pytorch/xla pull request #2786
Opened 2021-02-19 20:02 UTC by jysohn23

Nightly TPUVM broken due to API mismatch (https://github.com/tensorflow/tensorflow/commit/b70b22739cc41c004e9ff6a0ad6b599b308d47dd).

Also, XLA changed API and location for permutation utils we used to use:
* https://github.com/tensorflow/tensorflow/commit/231d3ab44db8c9d23525dcf454527e306794d2e8
* https://github.com/tensorflow/tensorflow/commit/9fcf66e16dfbd32ebf739bac3e2dd1db59c67360

We'll need to cherry-pick this one and others into r1.8 as public preview libtpu.so will be cut later.

2021-02-19 20:37 UTC, JackCaoG requested changes
I believe we want to make sure libtpu.so also works before updating tf and you are working on it right?

2021-02-19 20:37 UTC, JackCaoG commented on test/cpp/test_aten_xla_tensor.cpp
> -  EXPECT_TRUE(xla::IsPermutation(shuffle_data, n));
can you make it EXPECT_TRUE(shuffle_data.size() == n && xla::IsPermutation(shuffle_data)); same for the other place. This way we don't lose the size check.

2021-02-19 20:37 UTC, JackCaoG commented on torch_xla/csrc/helpers.h
> +    XLA_CHECK(xla::IsPermutation(permutation))
ditto

2021-02-19 20:49 UTC, jysohn23 commented
> I believe we want to make sure libtpu.so also works before updating tf and you are working on it right?

Yea, I hadn't sent it for review just yet because of that, I'll circle back once we figure out TPU device not found issue w/ TF sync.

2021-02-24 15:11 UTC, jysohn23 commented
Closing for now as the extent of the breakage syncing to TF head is bigger than expected. Continuing investigation internally.

2021-02-24 15:11 UTC, closed without merging