Add explicit lowerings for bitwise_not
pytorch/xla pull request #2893
Opened 2021-04-16 15:49 UTC by ezyang

See https://github.com/pytorch/pytorch/issues/56273
For now I just want to work around the issue, but it's worth
investigating further why XLA doesn't just get these lowerings
for free.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

2021-04-16 15:49 UTC, ezyang commented
cc @bdhirsh this will affect your codegen

2021-04-16 15:50 UTC, ezyang commented
cc @JackCaoG

2021-04-16 16:51 UTC, ezyang commented
I ran clang-format but apparently my version is wrong and it is still unhappy, can someone plz tell me how to get it or just run it on this PR for me, thx

2021-04-16 17:10 UTC, JackCaoG commented
Thanks @ezyang ! Could you try `clang-format-7` ? https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md#c-style-guide

2021-04-19 22:23 UTC, JackCaoG requested changes
Thanks @ezyang !

2021-04-19 22:23 UTC, JackCaoG commented on scripts/gen.py
> +    'bitwise_not': FuncOpts(),
I think you meant `bitwise_not_out` here?

2021-04-20 18:13 UTC, ezyang commented
This should get mooted by https://github.com/pytorch/pytorch/pull/56307

2021-04-22 17:35 UTC, closed without merging