Fix torch.where(bool, int64, 0.5)
pytorch/xla pull request #3208
Opened 2021-11-10 08:59 UTC by JackCaoG

This is to fix https://github.com/pytorch/xla/issues/3105.

Case this failed is 
```
bool_t = torch.tensor([True, False], device=device)
true_t = torch.tensor([10, 20], device=device)

t1 = torch.where(bool_t, true_t, 0.5)
```

2021-11-19 03:32 UTC, wonjoolee95 approved these changes
LGTM 👍

2022-02-08 02:04 UTC, JackCaoG commented
Need to resolve the conflict

2022-02-10 18:49 UTC, miladm requested changes
Thanks @JackCaoG!
LTGM

nit: shall we add this specific condition as a new test scenario to `TestWhere`?

2022-02-10 19:27 UTC, miladm commented on torch_xla/csrc/tensor_methods.cpp
> +  } else {
nit: you can drop this else block given the previous return.

2023-12-04 23:58 UTC, closed without merging