Provide op lowering for prelu
pytorch/xla pull request #3222
Opened 2021-11-22 10:02 UTC by wonjoolee95

2021-11-23 17:56 UTC, miladm commented
Adding @yeounoh here so he uses this PR as dev reference.

2021-11-24 02:54 UTC, miladm requested changes
Thanks @wonjoolee95. Looks good for the most part. I added a couple of nits.

2021-11-24 21:37 UTC, JackCaoG reviewed
LGTM after fix MIlad's comment

2021-11-30 03:31 UTC, wonjoolee95 commented on test/cpp/test_aten_xla_tensor.cpp
> +    torch::Tensor output = torch::prelu(input, weight);
Good catch! Updated.

2021-11-30 03:31 UTC, wonjoolee95 commented on test/cpp/test_aten_xla_tensor.cpp
> +    AllClose(input, xla_input);
Good point, makes sense. Updated.

2021-12-01 20:15 UTC, wonjoolee95 commented
Fixed comments and CircleCI builds seem good. Will merge these changes.

2021-12-01 20:15 UTC, merged