Add test to verify virtual device usage metrics
pytorch/xla pull request #4330
Opened 2022-12-14 19:38 UTC by steventk-g

2022-12-14 22:06 UTC, yeounoh requested changes
LGTM, requested to add another quick test case.

2022-12-15 00:18 UTC, steventk-g commented on test/test_xla_sharding.py
> +    self.assertNotEqual(met.counter_value("VirtualDeviceUsage"), 0)
Added a test for sharding on model weights. It looks like virtual device will still be used to delay the transfer of the model weights in `nn.Linear(128, 64).to(xm.xla_device())` until the sharding is applied.

2022-12-15 03:42 UTC, yeounoh commented on test/test_xla_sharding.py
> +    self.assertNotEqual(met.counter_value("VirtualDeviceUsage"), 0)
Nice!

2022-12-15 03:42 UTC, yeounoh approved these changes
LGTM

2022-12-15 19:05 UTC, JackCaoG approved these changes

2022-12-15 19:12 UTC, merged