Expose shard rank in XLAShard
pytorch/xla pull request #5654
Opened 2023-09-27 19:47 UTC by jonb377

To optimize distributed checkpoint writing, we should distribute the writes for replicated shards across the hosts tracking the shard. This PR exposes the rank of each shard, which can be used to select a host responsible for writing when preparing the global plan. `rank` here is defined to be among the hosts which contain the same shard, and the value depends on the type of sharding:
- `REPLICATED`: Since every host has a copy of the shard and there is no tiling, the rank is equal to the global device ordinal.
- `TILED`: When fully tiled, each shard lives only on a single device, so the rank is always 0.
- `PARTIAL`: Partial replication is the main use case for the rank. With this sharding type, the rank is taken from the last tile dimension, which indicates the replication group assignment.

Selecting the shard rank depends on the tiling assignment for partial replication, which is a small extension to the existing logic for `GetShardIndicesForDevices`. I opted to refactor this method to also return the shard's rank instead of declaring a new method to get the shard rank. 

Aside from the refactor for the return type, the actual logic for choosing shard rank is added to `ShardingUtil:: GetShardRankAndIndicesForDevices` in `torch_xla/csrc/xla_sharding_util.cpp`, and the change to add `rank` to `XLAShard` is in `xla_sharded_tensor.py`

2023-10-02 18:39 UTC, yeounoh commented
@jonb377 I have a suggestion: instead of overloading the term `rank` which is more generic for host processes in PyTorch, let's name it as `replica_id` which is essentially what you want and precise, imo.

2023-10-02 18:46 UTC, yeounoh requested changes
Will sync offline about https://github.com/pytorch/xla/pull/5654#issuecomment-1743564329

2023-10-02 21:59 UTC, yeounoh commented on torch_xla/csrc/init_python_bindings.cpp
> +  // global tensor as either a Python list of slices for each dimension or a
a list of (rank_id, Union[slice, elipsis]) tuples, or something like that.

2023-10-02 22:05 UTC, yeounoh approved these changes
LGTM

2023-10-03 19:47 UTC, merged

2023-10-03 21:12 UTC, jonb377 commented
Thanks @yeounoh!