Use `subprocess` for checking XLA supported devices.
pytorch/xla pull request #5960
Opened 2023-12-01 06:24 UTC by ysiraichi

Fix: #5943

In summary:

- Create a self-contained XLA device checking python script: check_xla_device.py
- Use `subprocess` for calling the checking script with different devices

2023-12-01 06:25 UTC, ysiraichi commented
cc @JackCaoG @miladm

2023-12-04 14:58 UTC, frgossen requested changes

2023-12-04 14:58 UTC, frgossen commented on benchmarks/util.py
> +  r = subprocess.run([sys.executable, python_file, devkind])
Why does this fix the issue? (I never understood why this failure appeared in the first place) 
I just want to make sure that we don't hide the error message in a subprocess and silently fail.

2023-12-05 03:45 UTC, vanbasten23 commented
I ran your repro https://github.com/pytorch/xla/issues/5943#issuecomment-1834697201 and I got:
```
root@xiowei-gpu:/ansible# PJRT_DEVICE=CUDA python test.py
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1701747812.339996    9300 tfrt_cpu_pjrt_client.cc:349] TfrtCpuClient created.
R: True
R: True
root@xiowei-gpu:/ansible#
```
Is it consistent with what you got?

2023-12-05 15:30 UTC, ysiraichi commented
No. I still get:

```
$ PJRT_DEVICE=CUDA python repro.py

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1701790031.458193  396674 tfrt_cpu_pjrt_client.cc:349] TfrtCpuClient created.
R: True
2023-12-05 15:27:11.514993: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NOT_INITIALIZED: initialization error
Traceback (most recent call last):
  File "repro.py", line 10, in _check
    q.put(bool(xm.get_xla_supported_devices(devkind=k)))
  File "xla/torch_xla/core/xla_model.py", line 99, in get_xla_supported_devices
    xla_devices = _DEVICES.value
  File "xla/torch_xla/utils/utils.py", line 29, in value
    self._value = self._gen_fn()
  File "xla/torch_xla/core/xla_model.py", line 20, in <lambda>
    _DEVICES = xu.LazyProperty(lambda: torch_xla._XLAC._xla_get_devices())
RuntimeError: Bad StatusOr access: FAILED_PRECONDITION: No visible GPU devices.
R: False
```

2023-12-05 16:06 UTC, ysiraichi commented
Maybe that has something to do with the underlying OS. Using `spawn` start method (default on some systems, I believe) does fix the issue. However I couldn't make it work with the benchmarking script.

2023-12-05 16:29 UTC, frgossen commented
> No. I still get:
> 
> ```
> $ PJRT_DEVICE=CUDA python repro.py
> 
> WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
> I0000 00:00:1701790031.458193  396674 tfrt_cpu_pjrt_client.cc:349] TfrtCpuClient created.
> R: True
> 2023-12-05 15:27:11.514993: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NOT_INITIALIZED: initialization error
> Traceback (most recent call last):
>   File "repro.py", line 10, in _check
>     q.put(bool(xm.get_xla_supported_devices(devkind=k)))
>   File "xla/torch_xla/core/xla_model.py", line 99, in get_xla_supported_devices
>     xla_devices = _DEVICES.value
>   File "xla/torch_xla/utils/utils.py", line 29, in value
>     self._value = self._gen_fn()
>   File "xla/torch_xla/core/xla_model.py", line 20, in <lambda>
>     _DEVICES = xu.LazyProperty(lambda: torch_xla._XLAC._xla_get_devices())
> RuntimeError: Bad StatusOr access: FAILED_PRECONDITION: No visible GPU devices.
> R: False
> ```

FWIW, I get this about every second time I run the script.

2023-12-05 17:05 UTC, vanbasten23 commented
@ysiraichi @frgossen iirc, can you check one thing? Have your env var PATH and LD_LIBRARY_PATH accounted for cuda, for example https://github.com/pytorch/xla/blob/master/docs/gpu.md#check-environment-variable?

2023-12-05 23:36 UTC, ysiraichi commented
For some reason, the same script started working for me (even without setting the environment variables). This is all looking very flaky.

2023-12-05 23:39 UTC, ysiraichi commented
That said, here's another reproducer:

```python
import traceback
import torch_xla.core.xla_model as xm

from multiprocessing import Process, Queue

import torch
print(torch.cuda.is_available())

def _check(q, k):
    import os
    os.environ["PJRT_DEVICE"] = k
    try:
        q.put(bool(xm.get_xla_supported_devices(devkind=k)))
    except:
        traceback.print_exc()
        q.put(False)

for devkind in ("CPU", "CUDA"):
    q = Queue()
    proc = Process(target=_check, args=(q, devkind))
    proc.start()
    proc.join(60)
    print("R:", q.get_nowait())
```

2023-12-05 23:40 UTC, ysiraichi commented
Apparently, this is a known limitation: you can't initialize a CUDA context before forking the process (and use the initialized context in the children process).

2023-12-06 15:46 UTC, frgossen commented
I have the env vars set and can confirm that it is very flaky for me.

2023-12-06 17:52 UTC, vanbasten23 commented
The change lgtm. @ysiraichi , could you add a comment about why we need to do this way?

2023-12-06 17:52 UTC, vanbasten23 approved these changes

2023-12-07 17:29 UTC, vanbasten23 commented
The CI build fails. Let me retrigger it

2023-12-08 00:15 UTC, ysiraichi commented
Yes. I had some PRs also fail after building successfully (operation cancelled, etc.). Pretty sure it's unrelated to the PR. Any thoughts?

2023-12-08 19:47 UTC, closed without merging

2023-12-08 19:47 UTC, ysiraichi commented
Closed due to [a timeout issue](https://github.com/pytorch/xla/pull/6061#issuecomment-1847632833). Re-opened the PR at #6068.