Gather more summary data when running `result_analyzer.py`.
pytorch/xla pull request #6001
Opened 2023-12-02 17:54 UTC by ysiraichi

This PR refactors and computes more summary data out of each timing sequence. More specifically, besides the median, we also compute and store: min, max, mean, and std.

2023-12-02 17:54 UTC, ysiraichi commented
cc @JackCaoG @miladm

2023-12-06 14:50 UTC, frgossen requested changes
Thanks for adding these. I realized that the `result_analyzer` is broken for some configurations, e.g. producing csv output. Would you mind adding a test for your change? It'd be great to have a start so we can all add tests over time.

2023-12-06 17:43 UTC, vanbasten23 commented
Wondering if you have compared the results before and after the change.

2023-12-06 17:43 UTC, vanbasten23 approved these changes

2023-12-06 22:15 UTC, ysiraichi commented
Here's a screenshot of the difference of one benchmark run. Note that, even though it's still there, `xla_median_trace_per_iter_time` was replaced by `median_trace_per_iter_time`.

![diff](https://github.com/pytorch/xla/assets/3337141/1e0783b0-5e2d-4c44-b1f9-9657a70e114e)

2023-12-06 22:20 UTC, ysiraichi commented
I propose that we refactor this script a bit further, so that:

- it summarizes the data from JSONL, into the same fieldnames
    - do we actually need the JSON output version?
- we don't need to explicitly describe the header

2023-12-06 22:59 UTC, frgossen commented
> I propose that we refactor this script a bit further, so that:
> 
> * it summarizes the data from JSONL, into the same fieldnames
With "the same fieldnames", do you mean to write it back to that original file? I think having this analysis as a second step is a good thing. We should eventually merge this with the aggregate script though 

>   * do we actually need the JSON output version?
Unless we have uses for both, it'd be good to have either CSV or JSON, not both. I have no preference. The aggregate script is based on CSV atm. 

> * we don't need to explicitly describe the header
I assume this is for CSV files? It's probably a good idea to have a header line to keep it readable.

2023-12-06 23:05 UTC, ysiraichi commented
> With "the same fieldnames", do you mean to write it back to that original file?

No, I mean the headers. At the moment, CSV and JSON outputs have different key-value pairs (JSON is hierarchically laid out).

> I assume this is for CSV files? It's probably a good idea to have a header line to keep it readable.

Yes. I mean, in the script, [we explicitly write the headers using `pd.Dataframe`](https://github.com/pytorch/xla/blob/fe4af0080af07f78ca2b614dd91b71885a3bbbb8/benchmarks/result_analyzer.py#L49). Instead, we can make the script work with whatever data was collected, without explicitly describing them in the **script**. The output would still have a headerline.

2023-12-08 14:38 UTC, golechwierowicz requested changes

2023-12-08 14:44 UTC, golechwierowicz commented on benchmarks/result_analyzer.py
> -    if "per_iter_cuda_time_s" in dataline["metrics"]:
You're right. I was surprised not to see the crude code :P Can you add a test to cover whether device time is analyzed?

2023-12-08 14:46 UTC, golechwierowicz approved these changes

2023-12-08 19:43 UTC, closed without merging