Add explicit shape check for index_copy
pytorch/xla pull request #6508
Opened 2024-02-09 04:32 UTC by wonjoolee95

As per https://pytorch.org/docs/stable/generated/torch.Tensor.index_copy_.html, the dim-th dimension of the tensor must have the same size as the length of index. PyTorch behavior: 
```
>>> import torch
>>> x = torch.zeros(5, 3)
>>> t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
>>> index = torch.tensor([0, 4, 2, 1])
>>> x.index_copy_(0, index, t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index_copy_(): Number of indices (4) should be equal to source.size(dim) (3)
```
Update the torch_xla's `index_copy` lowering to throw a similar error message.

One other check we may want is checking each value in the index tensor to be within the dimensions of the input tensor. But because torch_xla's lowering of `index_copy` uses `xla::Scatter` which requires torch_xla to do some broadcast, doing this bound check for each index seems a bit tricky. So for now, this PR will first add this explicit shape check only.

2024-02-12 07:43 UTC, miladm commented on torch_xla/csrc/aten_xla_type.cpp
> +            source_tensor_dims[dim] == index_tensor_dims[0])
For out of bound index issues, we need to verify the following test scenario is caught in tests.

```
x = torch.zeros(5, 3)
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 9, 2]) # the second index (i.e. 9) is out of bound as the first dim of x is 5.
x.index_copy_(0, index, t)
```

2024-02-12 07:43 UTC, miladm requested changes
thanks @wonjoolee95 added a comment.

2024-02-12 21:38 UTC, alanwaketan reviewed
Can we add a test case?

2024-02-12 21:38 UTC, alanwaketan commented on torch_xla/csrc/aten_xla_type.cpp
> +  absl::Span<const int64_t> index_tensor_dims =
Maybe we can just query the length of the index tensor as it should be a vector.

2024-08-15 20:49 UTC, wonjoolee95 commented
This PR just implements an out-of-range check `index_copy`, so we should be able to just fix the failing assertions and merge them. Or we can just close it. cc @miladm

2024-08-15 23:34 UTC, wonjoolee95 commented
I'll close this for now as it is not relevant, but feel free to re-open if necessary.

2024-08-15 23:34 UTC, closed without merging