Update torch_xla wheels to have the suffix +cxx11 instead of .cxx11
pytorch/xla pull request #8472
Opened 2024-12-09 20:54 UTC by bhavya01

Currently while running 
```pip3 install https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch_xla-2.6.0.dev20241028.cxx11-cp310-cp310-linux_x86_64.whl```
 I get this error 
```ERROR: Invalid requirement: 'torch-xla==2.6.0.dev20241209.cxx11': Expected end or semicolon (after version specifier) torch-xla==2.6.0.dev20241209.cxx11```

Renaming the wheels to this format fixes it.

2024-12-09 21:27 UTC, tengyifei commented
I see. Could you update the README in https://github.com/pytorch/xla/blob/master/README.md#use-nightly-build-with-c11-abi-after-10282024 too? Maybe add a section that from Dec 9 onwards, we'll again use a different syntax for nightly installation.

2024-12-09 21:27 UTC, tengyifei requested changes
I see. Could you update the README in https://github.com/pytorch/xla/blob/master/README.md#use-nightly-build-with-c11-abi-after-10282024 too? Maybe add a section that from Dec 9 onwards, we'll again use a different syntax for nightly installation.

2024-12-10 19:34 UTC, tengyifei approved these changes

2024-12-10 22:21 UTC, ManfeiBai approved these changes
Thanks, LGTM

2024-12-10 22:21 UTC, merged