[AdHoc] Test fix: clear metrics and simplify the replicated counter
pytorch/xla pull request #8478
Opened 2024-12-10 21:40 UTC by rpsilva-aws

In this PR, we ensure that metrics are cleared before the test is executed, and we align the assertion for `ExecuteReplicated` to not hardcode the expected execution pattern, similar to other SPMD tests (e.g. `test_dtensor_integration.py`).

2024-12-10 23:04 UTC, tengyifei approved these changes

2024-12-10 23:39 UTC, tengyifei commented
Discussed offline, the metric failure was due to a race condition. Let's remove the metric check since this test is meant to validate the sharding spec.

2024-12-10 23:39 UTC, tengyifei requested changes
Discussed offline, the metric failure was due to a race condition. Let's remove the metric check since this test is meant to validate the sharding spec.

2024-12-10 23:48 UTC, tengyifei approved these changes

2024-12-11 01:15 UTC, lsy323 approved these changes

2024-12-11 01:40 UTC, merged