training UX: automatic generating make_train_step
pytorch/xla pull request #8495
Opened 2024-12-17 03:56 UTC by qihqi

2025-01-02 19:22 UTC, tengyifei requested changes

2025-01-02 19:22 UTC, tengyifei commented on experimental/torch_xla2/examples/train_llama_torchtitan/train_llama.py
> +        dropout_p=0.0, is_causal=False,
What happens if `dropout_p` is not zero or when `is_causal` is `False`? Should we assert that their values matches the behavior of `splash_attention`?

2025-01-02 19:22 UTC, tengyifei commented on experimental/torch_xla2/torch_xla2/train.py
> +                    mark_fsdp_sharding_axis=None):
This seems fairly specific to the FSDP sharding scheme. What if my model input and output uses different sharding schemes? What if I want my model output to be 2D sharded? What if they are PyTrees?

Instead, I wonder if we could separate the sharding concern from `make_train_step`. For example, what if we had

```
def shard_input(fn, in_shardings) -> fn
def shard_output(fn, out_shardings) -> fn

# Alternatively, just a `shard` function where `in_shardings` and `out_shardings` semantics matches what's in https://jax.readthedocs.io/en/latest/jax.experimental.pjit.html
def shard(fn, in_shardings, out_shardings)
```

That could internally wrap any function (such as the model code) and then annotate the inputs or outputs with sharding annotations? Then the user could apply whatever sharding they want.

2025-01-02 19:22 UTC, tengyifei commented on experimental/torch_xla2/torch_xla2/train.py
> +          return (newh, *rest), torch.ones(1, device='jax')
Could the `torch.ones(1, ...)` simply be `None`? `None` is the base case of a PyTree and is what I managed to got working in `torch_xla`'s scan.

2025-01-16 22:06 UTC, tengyifei commented
Wondering if I should review this again

2025-01-17 00:55 UTC, qihqi commented on experimental/torch_xla2/torch_xla2/train.py
> +          return (newh, *rest), torch.ones(1, device='jax')
done.

2025-01-17 00:56 UTC, qihqi commented on experimental/torch_xla2/examples/train_llama_torchtitan/train_llama.py
> +        dropout_p=0.0, is_causal=False,
This bit is to show case that you can register your own override of op.
So the user is writing this bit and we assume the user would know which special case it applies to them.

2025-01-17 00:57 UTC, qihqi commented on experimental/torch_xla2/examples/train_llama_torchtitan/README.md
> +6. Precompile: call to `helpers.precompile_step`. This is not needed. If not used, then
done

2025-01-17 00:57 UTC, qihqi commented on experimental/torch_xla2/examples/train_llama_torchtitan/README.md
> +        #opt_state = torch_xla2.interop.call_jax(jax_optimizer.init, jittable_mod.params)
done.

2025-01-17 00:57 UTC, qihqi commented on experimental/torch_xla2/examples/train_llama_torchtitan/README.md
> +extra encantations so that we split an array to only the shards corresponding
done.

2025-01-17 00:57 UTC, qihqi commented on experimental/torch_xla2/examples/train_llama_torchtitan/README.md
> +When running on single-host, `jax.device_put` sufficies. Multi-host need some
done

2025-01-17 00:59 UTC, qihqi commented on experimental/torch_xla2/examples/basic_training_jax.py
> +train_step = interop.jax_jit(train_step, kwargs_for_jax_jit={'donate_argnums': (0, 2)})
You're right. The current issue is that sometimes I want to print out the stablehlo for inspection. So need to make the jax_jit'd object also to store the jax function. I'll followup.

2025-01-17 01:00 UTC, qihqi commented
> Wondering if I should review this again

Yes, PTAL, thanks!

2025-01-21 23:05 UTC, qihqi commented on experimental/torch_xla2/torch_xla2/train.py
> +                    mark_fsdp_sharding_axis=None):
moved sharding annotation to the client.

2025-01-21 23:09 UTC, tengyifei commented on experimental/torch_xla2/torch_xla2/train.py
> +  mark_fsdp_sharding_axis: str. A string name for marking sharding for
nit: obsolete comment

2025-01-21 23:10 UTC, tengyifei commented on experimental/torch_xla2/examples/train_llama_torchtitan/train_llama.py
> +        #opt_state = torch_xla2.interop.call_jax(jax_optimizer.init, jittable_mod.params)
ptal

2025-01-21 23:13 UTC, tengyifei approved these changes

2025-01-22 01:46 UTC, merged